### PR TITLE
Fixed #15

### LINKED ISSUE #15: feat: add our journey section
# Add Our Journey Section

## Overview
The website's landing page currently lacks a dedicated Our Journey section that highlights the chapter's milestones along our path. This issue involves adding the Our journey section to the landing page based on the provided Figma design, using Tailwind CSS for styling and layout.

## Task
Implement the Our Journey section with the following requirements:
- Ensure the design closely follows the Figma file, maintaining visual consistency with the rest of the landing page.
- Utilize Tailwind CSS utility classes for layout, typography, and spacing.
- Ensure the section is fully responsive and looks good across all screen sizes.
- Avoid using inline styles unless necessary.

### Figma design
https://www.figma.com/design/Nzahg0BeYXdUECGXRzLKsP/CYSCOM-main-UI?node-id=0-1&t=RgHhWSuukMqKvkAm-1

**Note: Issues are limited only to Cyscom members**

### PR DESCRIPTION
**Pull request by Ironpatriot06**
Made the our journey page and incorporated it in the website and it is responsive.😃

### CODE REVIEW

**Comment by ezhil56x** [comment]
image

Move journey section little bit below the first section, you could see the line visible in the first section

**Comment by shivam1608** [comment]
image

Just wanted to know why its different from figma design?

**Comment by ezhil56x** [comment]
@Ironpatriot06 Let's see if its possible to implement the design in figma file. If there are no possibilities to implement, we'll go with this

**Comment by shivam1608** [comment]
I tried implementing that but it breaks at some very specific breakpoints somehow otherwise it works.

https://github.com/shivam1608/cyscom-website/tree/dev

image

**Comment by ezhil56x** [comment]
@shivam1608 Looks good! Increase the height so that this section can take the full view and add some hover animations to the card like Our Mission section and create a PR

**Comment by shivam1608** [comment]
@ezhil56x done the changes in #20 👍

**Comment by ezhil56x** [comment]
Closing this pr in favour of #20. Good work @Ironpatriot06 @shivam1608

**Pull request closed without merging**
