### PR TITLE
Our Mission Section #14 

### PR DESCRIPTION
**Pull request by shivam1608**
### Additions ➕
- Our Mission Section  #14 

### Fixes 🕸️
- Linting
- Duplicate Class

### CODE REVIEW

**Review by ezhil56x — APPROVED** [review]
LGTM

**Comment by ezhil56x** [comment]
@shivam1608 Can you check if this is considered as a hacktoberfest contribution?

**Comment by shivam1608** [comment]
@ezhil56x its shows this

image
image

**Comment by ezhil56x** [comment]
Good to go!

**Pull request merged**
